# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup submodules
        run: git submodule update -i
        working-directory: ./tests
      - name: cmake googletest
        run: cmake -B ./tests/googletest -S ./tests/googletest
      - name: make googletest
        run: make -C ./tests/googletest
      - name: cmake project
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
      - name: make project
        run: make
      - name: Run googletest
        run: ctest -V
